<a href="https://colab.research.google.com/github/NoelYohan/PROJECTS/blob/main/Data_Preprocessing_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning with ANN

## Importing the libraries

In [53]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [54]:
tf.__version__

'2.18.0'

## Importing Dataset

In [55]:
data_set = pd.read_csv("AMerican Express User Exit Prediction.csv")
X = data_set.iloc[:,0:-1].values
y = data_set.iloc[:,-1].values

In [56]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]





## Handling Missing Data

## Encoding Categorical Data

### Gender Column : Label Encoding

In [57]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [58]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


### Georgraphy Column : One Hot Encoding

In [59]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [60]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


## Splitting data into Test set & Training Set


In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [62]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [73]:
print(X_train.shape)
print(y_train.shape)
print(type(X_train), type(y_train))

(7941, 11)
(7941,)
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


## ANN

### Intialization

In [76]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

### Adding input layer and first hidden layer

In [77]:
input_dim=X_train.shape[1]

### Adding Second Hidden Layer

In [79]:
model=Sequential([Dense(64,activation='relu',input_shape=(input_dim,)),
                  Dense(32,activation='relu'),
                  Dense(1,activation='sigmoid')])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### Adding Output Layer


In [66]:
##ann.add(tf.keras.layers.Dense(units = 5,activation='sigmoid'))

## ANN Training


### Compiling ANN

In [81]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_14 (Dense)                │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,881 (11.25 KB)

 Trainable params: 2,881 (11.25 KB)

 Non-trainable params: 0 (0.00 B)

### Training on Training Dataset

In [109]:
history=model.fit(X_train,y_train,batch_size=32, epochs=120)

Epoch 1/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9105 - loss: 0.3331
Epoch 2/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9083 - loss: 0.2804
Epoch 3/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9104 - loss: 0.2603
Epoch 4/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8991 - loss: 0.2967
Epoch 5/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9141 - loss: 0.2570
Epoch 6/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9094 - loss: 0.2552
Epoch 7/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9125 - loss: 0.2618
Epoch 8/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9060 - loss: 0.2562
Epoch 9/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9178 - loss: 0.2287
Epoch 10/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9128 - loss: 0.2384
Epoch 11/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9119 - loss: 0.2355
Epoch 12/120
249/249 ━━━━━━━━━━━━━━━━━━━

## Evaluating

In [110]:
loss,accuracy=model.evaluate(X_test,y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Accuracy: {accuracy:.4f}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8050 - loss: 0.7212
Test Loss: 0.6852
Accuracy: 0.8041


## Predictions

### Single Predictions

In [104]:
print(model.predict(sc.transform([[1.0, 0.0, 0.0, 447, 1, 31, 7, 0.0, 4, 1, 519360]]))>0.5)
predictions=model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[[False]]
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [105]:
Y_pred=model.predict(X_test)
Y_pred=(Y_pred>0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[1 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [1 1]]


## Confusion Matrix

In [106]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,Y_pred)
print(cm)
accuracy_score(y_test,Y_pred)

[[1389  184]
 [ 208  205]]


0.8026183282980867